Read the data with pandas and find features and target variables

In [ ]:
import pandas as pd
data = pd.read_csv("/train.csv")
data

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,...,1222,1890,668,13,4,19,1,1,0,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,...,915,1965,2032,11,10,16,1,1,1,2
1997,1911,0,0.9,1,1,1,36,0.7,108,8,...,868,1632,3057,9,1,5,1,1,0,3
1998,1512,0,0.9,0,4,1,46,0.1,145,5,...,336,670,869,18,10,19,1,1,1,0
1999,510,1,2.0,1,5,1,45,0.9,168,6,...,483,754,3919,19,4,2,1,1,1,3

In [ ]:
y=data['price_range']
y

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64

In [ ]:
x=data.drop('price_range',axis=1)
x

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,842,0,2.2,0,1,0,7,0.6,188,2,2,20,756,2549,9,7,19,0,0,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,6,905,1988,2631,17,3,7,1,1,0
2,563,1,0.5,1,2,1,41,0.9,145,5,6,1263,1716,2603,11,2,9,1,1,0
3,615,1,2.5,0,0,0,10,0.8,131,6,9,1216,1786,2769,16,8,11,1,0,0
4,1821,1,1.2,0,13,1,44,0.6,141,2,14,1208,1212,1411,8,2,15,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,14,1222,1890,668,13,4,19,1,1,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,3,915,1965,2032,11,10,16,1,1,1
1997,1911,0,0.9,1,1,1,36,0.7,108,8,3,868,1632,3057,9,1,5,1,1,0
1998,1512,0,0.9,0,4,1,46,0.1,145,5,5,336,670,869,18,10,19,1,1,1
1999,510,1,2.0,1,5,1,45,0.9,168,6,16,483,754,3919,19,4,2,1,1,1

Normalize the data with min-max scaling

In [ ]:
data_normalized=(x-x.min())/(x.max()-x.min())
data_normalized

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,0.227789,0.0,0.68,0.0,0.052632,0.0,0.080645,0.555556,0.900000,0.142857,0.10,0.010204,0.170895,0.612774,0.285714,0.388889,0.944444,0.0,0.0,1.0
1,0.347361,1.0,0.00,1.0,0.000000,1.0,0.822581,0.666667,0.466667,0.285714,0.30,0.461735,0.993324,0.634687,0.857143,0.166667,0.277778,1.0,1.0,0.0
2,0.041416,1.0,0.00,1.0,0.105263,1.0,0.629032,0.888889,0.541667,0.571429,0.30,0.644388,0.811749,0.627205,0.428571,0.111111,0.388889,1.0,1.0,0.0
3,0.076152,1.0,0.80,0.0,0.000000,0.0,0.129032,0.777778,0.425000,0.714286,0.45,0.620408,0.858478,0.671566,0.785714,0.444444,0.500000,1.0,0.0,0.0
4,0.881764,1.0,0.28,0.0,0.684211,1.0,0.677419,0.555556,0.508333,0.142857,0.70,0.616327,0.475300,0.308658,0.214286,0.111111,0.722222,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0.195725,1.0,0.00,1.0,0.000000,1.0,0.000000,0.777778,0.216667,0.714286,0.70,0.623469,0.927904,0.110102,0.571429,0.222222,0.944444,1.0,1.0,0.0
1996,0.977956,1.0,0.84,1.0,0.000000,0.0,0.596774,0.111111,0.891667,0.428571,0.15,0.466837,0.977971,0.474613,0.428571,0.555556,0.777778,1.0,1.0,1.0
1997,0.941884,0.0,0.16,1.0,0.052632,1.0,0.548387,0.666667,0.233333,1.000000,0.15,0.442857,0.755674,0.748530,0.285714,0.055556,0.166667,1.0,1.0,0.0
1998,0.675351,0.0,0.16,0.0,0.210526,1.0,0.709677,0.000000,0.541667,0.571429,0.25,0.171429,0.113485,0.163816,0.928571,0.555556,0.944444,1.0,1.0,1.0
1999,0.006012,1.0,0.60,1.0,0.263158,1.0,0.693548,0.888889,0.733333,0.714286,0.80,0.246429,0.169559,0.978888,1.000000,0.222222,0.000000,1.0,1.0,1.0

Split the data into train and test.

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.5,random_state=42)
x_train,x_test,y_train,y_test

(      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
 440            1310     1          2.3         1   6       0          57
 573            1900     1          0.5         1   0       1          55
 946            1625     1          0.5         1   2       1          50
 997            1068     0          0.5         1   0       1          19
 503            1438     0          2.2         0   0       1          32
 ...             ...   ...          ...       ...  ..     ...         ...
 1130           1975     1          1.9         1   2       0          31
 1294            589     1          0.5         0   1       1          59
 860            1829     1          0.5         0   0       1          15
 1459           1927     0          0.9         1   3       0          11
 1126            635     1          0.6         1   1       1          50

       m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
 440     0.9        135        8   9        449       889  1175    16     0
 573     0.9        171        1   1        934      1241  3917    15     5
 946     0.1        107        8  17          8      1219   670    16     3
 997     0.9        197        8   9        322       875  1209    19    12
 503     0.6        176        7   6        683      1663   869    19    13
 ...     ...        ...      ...  ..        ...       ...   ...   ...   ...
 1130    0.9        151        1  17        775      1607  3022    13     5
 1294    0.7        146        8   4        759      1858   362    16    10
 860     0.4        160        5   7        729      1267  2080    16    11
 1459    0.4        190        8  12        491      1506  2916    16    11
 1126    0.3         97        5  13        193       989  2107    13    12

       talk_time  three_g  touch_screen  wifi
 440           8        0             0     0
 573          18        1             0     1
 946           8        1             0     0
 997          12        1             1     0
 503           9        1             1     1
 ...         ...      ...           ...   ...
 1130         19        0             0     1
 1294          6        1             1     1
 860          12        1             0     1
 1459         18        0             1     1
 1126         12        1             0     0

 [1000 rows x 20 columns],
       battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
 1860           1646     0          2.5         0   3       1          25
 353            1182     0          0.5         0   7       1           8
 1333           1972     0          2.9         0   9       0          14
 905             989     1          2.0         0   4       0          17
 1289            615     1          0.5         1   7       0          58
 ...             ...   ...          ...       ...  ..     ...         ...
 25              961     1          1.4         1   0       1          57
 1858           1615     1          2.8         0   3       0           9
 714            1188     1          1.4         1   0       1           9
 1009           1881     0          2.2         0   4       0          51
 193            1523     1          2.4         0   5       1          57

       m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
 1860    0.6        200        2   5        211      1608   686     8     6
 353     0.5        138        8  16        275       986  2563    19    17
 1333    0.4        196        7  18        293       952  1316     8     1
 905     0.2        166        3  19        256      1394  3892    18     7
 1289    0.5        130        5   8       1021      1958  1906    14     5
 ...     ...        ...      ...  ..        ...       ...   ...   ...   ...
 25      0.6        114        8   3        291      1434  2782    18     9
 1858    0.9        117        1  13        542       678  2948     8     3
 714     0.6        114        2   0       1339      1558  2896    12    11
 1009    0.3        158        5   7        477      1553  1229    12     0
 193     0.2        117        2   6        247       539  3971    18    12

       talk_time  three_g  touch_screen  wifi
 1860         11        1             1     0
 353          19        1             0     0
 1333          8        1             1     0
 905          19        1             1     0
 1289          5        1             0     0
 ...         ...      ...           ...   ...
 25            7        1             1     1
 1858          3        1             1     0
 714          16        1             0     1
 1009         14        1             0     0
 193          10        1             1     1

 [1000 rows x 20 columns],
 440     0
 573     3
 946     0
 997     0
 503     0
        ..
 1130    3
 1294    0
 860     2
 1459    3
 1126    1
 Name: price_range, Length: 1000, dtype: int64,
 1860    0
 353     2
 1333    1
 905     3
 1289    1
        ..
 25      2
 1858    2
 714     3
 1009    1
 193     3
 Name: price_range, Length: 1000, dtype: int64)

question-2:
Read the data with pandas and describe the data

In [ ]:
import pandas as pd
data = pd.read_csv("/content/sample_data/california_housing_test.csv")
data

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

Find the target and features

In [ ]:
y1=data['median_house_value']
y

0       344700.0
1       176500.0
2       270500.0
3       330000.0
4        81700.0
          ...
2995    225000.0
2996    237200.0
2997     62000.0
2998    162500.0
2999    500001.0
Name: median_house_value, Length: 3000, dtype: float64

In [ ]:
x1=data.drop('median_house_value',axis=1)
x

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375
...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608

Find data type and shape of each column

In [ ]:
import numpy as np
print(y.dtypes)
print(x.dtypes)
print(y.shape)
print(x.shape)

int64
battery_power      int64
blue               int64
clock_speed      float64
dual_sim           int64
fc                 int64
four_g             int64
int_memory         int64
m_dep            float64
mobile_wt          int64
n_cores            int64
pc                 int64
px_height          int64
px_width           int64
ram                int64
sc_h               int64
sc_w               int64
talk_time          int64
three_g            int64
touch_screen       int64
wifi               int64
dtype: object
(2000,)
(2000, 20)

Find the null values (if yes fill the null values with ‘0’ or mean of that column)

In [ ]:
x.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
dtype: int64

Normalize all the features

In [ ]:
data_normalized=(x-x.min())/(x.max()-x.min())
data_normalized

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
0,0.219814,0.513889,0.509804,0.127414,0.121654,0.128416,0.122565,0.421277
1,0.606811,0.181624,0.823529,0.049402,0.056858,0.067393,0.055804,0.213728
2,0.657379,0.130342,0.509804,0.117691,0.093225,0.123973,0.100041,0.365064
3,0.600619,0.134615,0.529412,0.002004,0.002400,0.003688,0.001826,0.388684
4,0.465428,0.402778,0.352941,0.040566,0.044674,0.070830,0.047687,0.168108
...,...,...,...,...,...,...,...,...
2995,0.445820,0.198718,0.431373,0.047431,0.118147,0.105029,0.122768,0.046834
2996,0.623323,0.160256,0.509804,0.172481,0.199372,0.292624,0.209821,0.199356
2997,0.462332,0.399573,0.176471,0.031205,0.036736,0.057670,0.044237,0.123419
2998,0.728586,0.164530,0.764706,0.002956,0.002215,0.003437,0.002435,0.191094
2999,0.469556,0.198718,0.803922,0.057778,0.048182,0.062699,0.052354,0.555916

Split the data into train and test.

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.5,random_state=42)
x_train,x_test,y_train,y_test

(      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
 53      -118.17     33.80                26.0       1589.0           380.0
 258     -116.63     33.89                22.0       1540.0           364.0
 505     -118.18     34.05                41.0        762.0           147.0
 752     -118.28     33.93                42.0       1898.0           460.0
 1978    -120.97     38.91                 7.0       4341.0           716.0
 ...         ...       ...                 ...          ...             ...
 1638    -121.81     37.25                 5.0       1975.0           520.0
 1095    -118.38     34.06                29.0       3946.0          1008.0
 1130    -117.80     34.15                14.0       7876.0          1253.0
 1294    -122.25     38.16                17.0       4459.0           944.0
 860     -118.43     34.01                43.0       1487.0           242.0

       population  households  median_income
 53         883.0       366.0         3.5313
 258        610.0       268.0         1.5227
 505        817.0       176.0         3.7500
 752       1503.0       429.0         2.5179
 1978      1978.0       682.0         4.8311
 ...          ...         ...            ...
 1638       861.0       440.0         4.4565
 1095      1676.0       876.0         2.7824
 1130      3699.0      1162.0         5.5423
 1294      1812.0       888.0         2.9375
 860        675.0       247.0         5.3403

 [1500 rows x 8 columns],
       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
 1801    -121.68     37.93                44.0       1014.0           225.0
 1190    -117.28     34.26                18.0       3895.0           689.0
 1817    -122.10     37.61                35.0       2361.0           458.0
 251     -118.29     33.88                36.0       1751.0           438.0
 2505    -118.40     33.99                39.0       1613.0           380.0
 ...         ...       ...                 ...          ...             ...
 1043    -121.37     38.57                22.0       4899.0           847.0
 2496    -122.27     41.20                52.0       4513.0           985.0
 2260    -121.03     37.67                24.0       2162.0           459.0
 2121    -122.20     37.77                41.0       1547.0           415.0
 1070    -122.19     37.48                38.0       1300.0           269.0

       population  households  median_income
 1801       704.0       238.0         1.6554
 1190      1086.0       375.0         3.3672
 1817      1727.0       467.0         4.5281
 251       1175.0       419.0         3.0739
 2505      1113.0       356.0         2.8250
 ...          ...         ...            ...
 1043      1701.0       826.0         5.2449
 2496      1926.0       815.0         1.5923
 2260      1468.0       441.0         3.1857
 2121      1024.0       341.0         2.0562
 1070       608.0       292.0         4.5568

 [1500 rows x 8 columns],
 53      187500.0
 258      71000.0
 505     123100.0
 752      97400.0
 1978    172200.0
           ...
 1638    159000.0
 1095    450000.0
 1130    248700.0
 1294    106700.0
 860     489800.0
 Name: median_house_value, Length: 1500, dtype: float64,
 1801    119400.0
 1190    133600.0
 1817    173600.0
 251     218600.0
 2505    276700.0
           ...
 1043    387000.0
 2496     56000.0
 2260     98300.0
 2121    102000.0
 1070    286900.0
 Name: median_house_value, Length: 1500, dtype: float64)